### PR TITLE
Refactoring lib

### PR DESCRIPTION
**Pull request by jriga**
* Use `operator.itemgetter`

* Use generators to get holidays and work_days

### CODE REVIEW

**Comment by ushkarev** [comment]
Hello @jriga, what's your motivation for using generators in this fashion?

**Comment by jriga** [comment]
For a project I'm looking after we needed to have a stream of public holidays and workdays for processing. 
I used the generator as a shortcut for these 2 methods instead of having to create a couple of Iterable classes.

**Comment by ushkarev** [comment]
Ah I see. In my opinion, I don't think generators will provide much benefit as the _base_ mechanism for filtering and yielding dates given that all the source data is already in memory. I do see how an infinite generator of working days could be useful, however it makes more sense to me to do that on top of the existing methods. Additionally, it's clearer to separate methods that go into the future from those that go into the past (as opposed to using an argument) – it would follow the pattern of existing methods. How about this #12

**Comment by jriga** [comment]
Yeah that works :+1: 
Closing this PR is favour of #12

**Comment by ushkarev** [comment]
New version up on [PyPI](https://pypi.org/project/govuk-bank-holidays/)

**Pull request closed without merging**
